<?php
/**
 * DomainDataRetrievalScreenshotResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * URLSLAB API
 *
 * optimize your website with SEO
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.41
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DomainDataRetrievalScreenshotResponseTest Class Doc Comment
 *
 * @category    Class
 * @description DomainDataRetrievalScreenshotResponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DomainDataRetrievalScreenshotResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DomainDataRetrievalScreenshotResponse"
     */
    public function testDomainDataRetrievalScreenshotResponse()
    {
    }

    /**
     * Test attribute "domain_id"
     */
    public function testPropertyDomainId()
    {
    }

    /**
     * Test attribute "url_id"
     */
    public function testPropertyUrlId()
    {
    }

    /**
     * Test attribute "screenshot_id"
     */
    public function testPropertyScreenshotId()
    {
    }

    /**
     * Test attribute "url_title"
     */
    public function testPropertyUrlTitle()
    {
    }

    /**
     * Test attribute "url_meta_description"
     */
    public function testPropertyUrlMetaDescription()
    {
    }

    /**
     * Test attribute "screenshot_status"
     */
    public function testPropertyScreenshotStatus()
    {
    }
}
