<?php
/**
 * DomainScheduleScheduleConfTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * URLSLAB API
 *
 * optimize your website with SEO
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.41
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DomainScheduleScheduleConfTest Class Doc Comment
 *
 * @category    Class
 * @description DomainScheduleScheduleConf
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DomainScheduleScheduleConfTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DomainScheduleScheduleConf"
     */
    public function testDomainScheduleScheduleConf()
    {
    }

    /**
     * Test attribute "urls"
     */
    public function testPropertyUrls()
    {
    }

    /**
     * Test attribute "link_following_strategy"
     */
    public function testPropertyLinkFollowingStrategy()
    {
    }

    /**
     * Test attribute "sitemaps"
     */
    public function testPropertySitemaps()
    {
    }

    /**
     * Test attribute "all_sitemaps"
     */
    public function testPropertyAllSitemaps()
    {
    }

    /**
     * Test attribute "take_screenshot"
     */
    public function testPropertyTakeScreenshot()
    {
    }

    /**
     * Test attribute "fetch_text"
     */
    public function testPropertyFetchText()
    {
    }

    /**
     * Test attribute "scan_speed_per_minute"
     */
    public function testPropertyScanSpeedPerMinute()
    {
    }

    /**
     * Test attribute "scan_frequency"
     */
    public function testPropertyScanFrequency()
    {
    }
}
