<?php
/**
 * DomainDataRetrievalSerpApiQueryHistoricalMetricsTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * URLSLAB API
 *
 * optimize your website with SEO
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DomainDataRetrievalSerpApiQueryHistoricalMetricsTest Class Doc Comment
 *
 * @category    Class
 * @description DomainDataRetrievalSerpApiQueryHistoricalMetrics
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DomainDataRetrievalSerpApiQueryHistoricalMetricsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DomainDataRetrievalSerpApiQueryHistoricalMetrics"
     */
    public function testDomainDataRetrievalSerpApiQueryHistoricalMetrics()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "competition_index"
     */
    public function testPropertyCompetitionIndex()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "competition_level"
     */
    public function testPropertyCompetitionLevel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_monthly_searches"
     */
    public function testPropertyAvgMonthlySearches()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "low_top_of_page_bid_micros"
     */
    public function testPropertyLowTopOfPageBidMicros()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "high_top_of_page_bid_micros"
     */
    public function testPropertyHighTopOfPageBidMicros()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_cpc_micros"
     */
    public function testPropertyAvgCpcMicros()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "monthly_search_volumes"
     */
    public function testPropertyMonthlySearchVolumes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
