<?php
/**
 * PublicAssetsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * URLSLAB API
 *
 * optimize your website with SEO
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.41
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * PublicAssetsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PublicAssetsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for loadCarouselThumbnail
     *
     * Fetching thumbnail of carousel screenshot of url.
     *
     */
    public function testLoadCarouselThumbnail()
    {
    }

    /**
     * Test case for loadFullPageThumbnail
     *
     * Fetching thumbnail of fullpage screenshot of url.
     *
     */
    public function testLoadFullPageThumbnail()
    {
    }

    /**
     * Test case for loadImageCarousel
     *
     * Fetching carousel screenshot of url.
     *
     */
    public function testLoadImageCarousel()
    {
    }

    /**
     * Test case for loadOriginalImage
     *
     * Fetching fullpage screenshot of url.
     *
     */
    public function testLoadOriginalImage()
    {
    }

    /**
     * Test case for loadTechnologyLogo
     *
     * Fetching icon logo of technology.
     *
     */
    public function testLoadTechnologyLogo()
    {
    }
}
